export const runStatus = {
  CREATING: "CREATING",
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  STOPPED: "STOPPED",
  FINISHED: "FINISHED",
  ERROR: "ERROR"
};

export const runAgentStatus = {
  PROCESSING: "PROCESSING",
  RUNNING: "RUNNING",
  FINISHED: "FINISHED",
  ERROR: "ERROR"
};

export const agentStatus = {
  CREATING: "CREATING",
  AVAILABLE: "AVAILABLE",
  PROCESSING_EVENT: "PROCESSING_EVENT",
  RUNNING_TEST: "RUNNING_TEST",
  UNAVAILABLE: "UNAVAILABLE",
  DISABLED: "DISABLED"
};

export const agentLogLevel = {
  DEBUG: "DEBUG",
  INFO: "INFO",
  WARNING: "WARNING",
  ERROR: "ERROR",
  CRITICAL: "CRITICAL"
};

export const userRole = {
  USER: "USER",
  ADMIN: "ADMIN"
};
