export const runStatus = {
  CREATING: "CREATING",
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  STOPPED: "STOPPED",
  FINISHED: "FINISHED"
};

export const agentStatus = {
  CREATING: "CREATING",
  AVAILABLE: "AVAILABLE",
  PROCESSING_EVENT: "PROCESSING_EVENT",
  RUNNING_TEST: "RUNNING_TEST",
  UNAVAILABLE: "UNAVAILABLE"
};

export const agentLogLevel = {
  DEBUG: "DEBUG",
  INFO: "INFO",
  WARNING: "WARNING",
  ERROR: "ERROR",
  CRITICAL: "CRITICAL"
};
