# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Python Agent
  - package-ecosystem: "pip"
    directory: "/agent"
    schedule:
      interval: "weekly"
    reviewers:
      - "vitaliimelnychuk"
      - "Farfetch/team-maestro"

  # Python Flask WEB API
  - package-ecosystem: "pip"
    directory: "/web/api"
    schedule:
      interval: "weekly"
    reviewers:
      - "vitaliimelnychuk"
      - "Farfetch/team-maestro"

  # React.js WEB Frontend
  - package-ecosystem: "npm"
    directory: "/web/frontend"
    schedule:
      interval: "weekly"
    reviewers:
      - "vitaliimelnychuk"
      - "Farfetch/team-maestro"

  # Website
  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
    reviewers:
      - "vitaliimelnychuk"
      - "Farfetch/team-maestro"