# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Maestro Frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/frontend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: "yarn"

      - name: Intall dependacies
        run: yarn install

      - name: Run linting checks
        run: yarn lint

      - name: Run formatting checks
        run: yarn format
