name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  api:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/api

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Intall dependacies
        run: make deps

      - name: Run linting checks
        run: make lint

      - name: Run formatting checks
        run: make format

      - name: Run tests
        run: make test

  frontend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/frontend

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: "yarn"
          cache-dependency-path: web/frontend/yarn.lock

      - name: Intall dependacies
        run: yarn install

      - name: Run linting checks
        run: yarn lint

      - name: Run formatting checks
        run: yarn format

      - name: Run tests
        run: CI=true yarn test
