name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  api:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/api

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.9.5"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip==22.0.4
          pip install pipenv==2022.3.23

      - name: Install dependacies
        run: make deps

      - name: Run linting checks
        run: make lint

      - name: Run formatting checks
        run: make format

      - name: Run tests
        run: make test

      - name: Generate coverage
        run: make coverage-xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./web/api/coverage.xml
          language: python

  agent:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./agent

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.9.5"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip==22.0.4
          pip install pipenv==2022.3.23

      - name: Install dependacies
        run: make deps

      - name: Run linting checks
        run: make lint

      - name: Run formatting checks
        run: make format

      - name: Run tests
        run: make test

      - name: Generate coverage
        run: make coverage-xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./agent/coverage.xml
          language: python

  cli:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.9.5"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip==22.0.4
          pip install pipenv==2022.3.23

      - name: Install dependacies
        run: make deps

      - name: Run linting checks
        run: make lint

      - name: Run formatting checks
        run: make format

      - name: Run tests
        run: make test

      - name: Generate coverage
        run: make coverage-xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./cli/coverage.xml
          language: python

  frontend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/frontend

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: "yarn"
          cache-dependency-path: web/frontend/yarn.lock

      - name: Intall dependacies
        run: yarn install

      - name: Run linting checks
        run: yarn lint

      - name: Run formatting checks
        run: yarn format

      - name: Run tests
        run: CI=true yarn test

      - name: Generate coverage
        run: yarn coverage

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./web/frontend/coverage/lcov.info
          language: javascript

  site:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: "yarn"
          cache-dependency-path: site/yarn.lock

      - name: Install dependacies
        run: yarn install

      - name: Run formatting checks
        run: yarn format

      - name: Build static
        run: yarn build

  backendlistener:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jmeter/plugins/jmeter-backendlistener-maestro
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify

  prose:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Vale
        uses: errata-ai/vale-action@v2.0.1
        with:
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

