name: Deploy

on:
  push:
    branches:
      - master
      - release-*
    paths:
      - ".github/workflows/deploy.yml"
      - "docs/**"
      - "site/**"

jobs:
  site:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
          cache: "yarn"
          cache-dependency-path: site/yarn.lock

      - name: Install dependacies
        run: yarn install

      - name: Run formatting checks
        run: yarn format

      - name: Build static
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/build
