name: Publish

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - release-*
    workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_REPOSITORY: maestro
      # TODO: Get version from tag that triggered workflow
      DOCKER_HUB_VERSION: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Set Env Variables
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo ${{ steps.get_version.outputs.VERSION }}
          echo "DOCKER_HUB_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_HUB_VERSION }}" >> $GITHUB_ENV

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./web
      #     push: true
      #     tags: ${{ env.DOCKER_HUB_TAG }}
      # cache-from: type=registry,ref=${{ env.DOCKER_HUB_TAG }}
      # cache-to: type=inline
